# Generated by Django 5.2.9 on 2026-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation_tracker', '0005_alter_curationpublicationannotation_curation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationpublicationannotation',
            name='second_level_curation_status',
            field=models.CharField(blank=True, choices=[('Awaiting curation', 'Awaiting curation'), ('Curation done', 'Curation done'), ('Determined ineligible', 'Determined ineligible'), ('Outstanding curation query', 'Outstanding curation query'), ('Pending author response', 'Pending author response'), ('Skipped', 'Skipped'), ('Undergoing curation', 'Undergoing curation')], default=None, max_length=50, null=True, verbose_name='Second Level Curation Status'),
        ),
    ]
