stages:
  - test

include:
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

variables:
  DS_ENFORCE_NEW_ANALYZER: 'true'
  GITLAB_ADVANCED_SAST_ENABLED: 'true'

# Pin all three jobs to the same stage
sast:
  stage: test
  artifacts:
    name: sast
    paths:
      - gl-sast-report.json
    reports:
      sast: gl-sast-report.json
    when: always

secret_detection:
  stage: test

dependency_scanning:
  stage: test