# Generated by Django 4.1.10 on 2023-10-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Performance Metric Name'),
        ),
    ]
