# Generated by Django 4.2.10 on 2024-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_metric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='efotrait_count',
            field=models.IntegerField(default=0, verbose_name='Number of new EFO traits released'),
        ),
    ]
